#ifndef ERRORS_H
  #define ERRORS_h

#include <registers.h>

typedef void (*error_callback_t)(int);
void error_handler(int error);

#define ERROR_CALLBACK(fn, error) \
  if (fn)\
    fn(error); \
  else \
    error_handler(error);

// USB INITIALIZATION ERROR
#define E_USB_INIT 100
#define E_USB_REGISTER_CLASS 101
#define E_USB_REGISTER_INTERFACE 102
#define E_USB_START 103

// USB TRANSMIT ERROR
#define E_USB_TRANSMIT_BUSY 120
#define E_USB_TRANSMIT_FAIL 121

// USB HAL CALBACK ERROR
#define E_USB_HAL_PCD_HS 130

// USB HAL RECEIVE ERROR
#define E_USB_RECEIVE_ERROR 140

// USB HAL LOCK ERROR
#define E_USB_LOCK_ERROR 150

// USB HAL RECEIVE PROCESS BUSY
#define E_USB_RECEIVE_PROC_BUSY 160

// USB BYTE CHUNK SENDING
#define E_USB_SEND_CHUNK_INIT_BUSY 170
#define E_USB_SEND_CHUNK_SEND_FAIL 171
#define E_USB_SEND_CHUNK_BUSY 172
#define E_USB_SEND_CHUNK_INIT_TIMEOUT 173
#define E_USB_SEND_CHUNK_TIMEOUT 174

// UART1 ERROR SENDING
#define E_UART1_BUSY 200
#define E_UART1_LOCKED 201
#define E_UART1_TIMEOUT 202
#define E_UART1_DMA1_CH4_TRANSMIT_ERROR 210
#define E_UART1_RECEIVE_ERROR_BASE 224 // Last 4 bits handles  ORE | NE | FE | PE in USART1_SR Page 818
  #define E_UART1_RECEIVE_ERROR_PARITY (E_UART1_RECEIVE_ERROR_BASE | PE)
  #define E_UART1_RECEIVE_ERROR_FRAME (E_UART1_RECEIVE_ERROR_BASE | FE)
  #define E_UART1_RECEIVE_ERROR_NOISE (E_UART1_RECEIVE_ERROR_BASE | NE)
  #define E_UART1_RECEIVE_ERROR_OVERUN (E_UART1_RECEIVE_ERROR_BASE | ORE)

#define E_UART1_DMA1_CH5_RECEIVE_ERROR 230
///////////////////////////////////

// OLED ERRORS

#define E_OLED_BUFFER_TRANSFER_BUSY -50
#define E_OLED_BUFFER_TRANSFER_BUSY_TIMEOUT -51
#define E_OLED_BUFFER_BUSY_TIMEOUT -52
#define E_OLED_INIT_FAILED -53
#define E_OLED_NOT_INITIALIZED -54
#define E_OLED_CURSOR_PRINTF_LOCK_TIMEOUT -55
#define E_OLED_CURSOR_FLUSH_UPDATE_TIMEOUT -56

///////////////////////////////////

// STD OUT ERRORS

#define E_INVALID_OLED_PRINTF_BUF_SIZE -100
#define E_OLED_PRINTF_BUFFER_ACCESS_TIMEOUT -101
#define E_INVALID_OLED_CURSOR_PRINTF_BUF_SIZE -102
#define E_OLED_PRINTF_SET_CURSOR_FLUSH_BUSY -103 

///////////////////////////////////

// ERROR IN PROCESS
#define PROCESS_BUSY 90
///////////////////////////////////

// SYS QUEUE ERRORS
#define E_SYS_QUEUE_FULL 80
#define E_SYS_ADD_QUEUE_TIMEOUT_OR_GLOBAL_LOCK 81
#define E_SYS_RUN_QUEUE_TIMEOUT 84
#define E_SYS_ADD_QUEUE_NOT_RUNNING 85
#define E_SYS_QUEUE_QUEUE_OFF 86
///////////////////////////////////

// MASTER RS485 ERRORS
#define E_MASTER_MODBUS_BUSY 400
#define E_MASTER_INVALID_SLAVE_ADDRESS 401
#define E_MASTER_INVALID_NUMBER_OF_COILS 402
#define E_MASTER_INVALID_RECEIVE_SLAVE_ADDRESS 403
#define E_UNEXPECTED_READ_COILS_FUNCTION 404
#define E_INVALID_READ_COILS_DATA_SIZE 405
#define E_INVALID_READ_COILS_CRC 406
#define E_UNEXPECTED_READ_COILS_ERROR_CODE 407
#define E_UNEXPECTED_DISCRETE_INPUTS_FUNCTION 408
#define E_MASTER_INVALID_NUMBER_OF_DISCRETE_INPUTS 409
#define E_UNEXPECTED_READ_DISCRETE_INPUTS_ERROR_CODE 410
#define E_INVALID_DISCRETE_INPUTS_DATA_SIZE 411
#define E_INVALID_DISCRETE_INPUTS_CRC 412
#define E_UNEXPECTED_READ_HOLDING_REGISTERS_ERROR_CODE 413
#define E_UNEXPECTED_READ_HOLDING_REGISTERS_FUNCTION 414
#define E_INVALID_READ_HOLDING_REGISTERS_DATA_SIZE 415
#define E_INVALID_READ_HOLDING_REGISTERS_CRC 416
#define E_MASTER_INVALID_NUMBER_OF_HOLDING_REGISTERS 417
#define E_MASTER_INVALID_NUMBER_OF_INPUT_REGISTERS 418
#define E_UNEXPECTED_READ_INPUT_REGISTERS_ERROR_CODE 419
#define E_UNEXPECTED_READ_INPUT_REGISTERS_FUNCTION 420
#define E_INVALID_READ_INPUT_REGISTERS_DATA_SIZE 421
#define E_INVALID_READ_INPUT_REGISTERS_CRC 422
#define E_UNEXPECTED_FUNCTION 430
#define E_UNEXPECTED_RECEIVE_FUNCTION 430
///////////////////////////////////

#define E_NOT_IMPLEMENTED -1

void error_handler(int);

#endif

