#ifndef ERRORS_H
  #define ERRORS_h

#include <registers.h>

typedef void (*error_callback_t)(int);
void error_handler(int error);

#define ERROR_CALLBACK(fn, error) \
  if (fn)\
    fn(error); \
  else \
    error_handler(error);

// USB INITIALIZATION ERROR
#define E_USB_INIT 100
#define E_USB_REGISTER_CLASS 101
#define E_USB_REGISTER_INTERFACE 102
#define E_USB_START 103

// USB TRANSMIT ERROR
#define E_USB_TRANSMIT_BUSY 120
#define E_USB_TRANSMIT_FAIL 121

// USB HAL CALBACK ERROR
#define E_USB_HAL_PCD_HS 130

// USB HAL RECEIVE ERROR
#define E_USB_RECEIVE_ERROR 140

// USB HAL LOCK ERROR
#define E_USB_LOCK_ERROR 150

// USB HAL RECEIVE PROCESS BUSY
#define E_USB_RECEIVE_PROC_BUSY 160

// USB BYTE CHUNK SENDING
#define E_USB_SEND_CHUNK_INIT_BUSY 170
#define E_USB_SEND_CHUNK_SEND_FAIL 171
#define E_USB_SEND_CHUNK_BUSY 172
#define E_USB_SEND_CHUNK_INIT_TIMEOUT 173
#define E_USB_SEND_CHUNK_TIMEOUT 174

// UART1 ERROR SENDING
#define E_UART1_BUSY 200
#define E_UART1_LOCKED 201
#define E_UART1_TIMEOUT 202
#define E_UART1_DMA1_CH4_TRANSMIT_ERROR 210
#define E_UART1_RECEIVE_ERROR_BASE 224 // Last 4 bits handles  ORE | NE | FE | PE in USART1_SR Page 818
  #define E_UART1_RECEIVE_ERROR_PARITY (E_UART1_RECEIVE_ERROR_BASE | PE)
  #define E_UART1_RECEIVE_ERROR_FRAME (E_UART1_RECEIVE_ERROR_BASE | FE)
  #define E_UART1_RECEIVE_ERROR_NOISE (E_UART1_RECEIVE_ERROR_BASE | NE)
  #define E_UART1_RECEIVE_ERROR_OVERUN (E_UART1_RECEIVE_ERROR_BASE | ORE)
#define E_UART1_RECEIVE_ERROR_BASE_LIMIT (E_UART1_RECEIVE_ERROR_PARITY|E_UART1_RECEIVE_ERROR_FRAME|E_UART1_RECEIVE_ERROR_NOISE|E_UART1_RECEIVE_ERROR_OVERUN)

#define E_UART1_DMA1_CH5_RECEIVE_ERROR 250

_Static_assert(E_UART1_DMA1_CH5_RECEIVE_ERROR > E_UART1_RECEIVE_ERROR_BASE_LIMIT, "Error number conflict E_UART1_DMA1_CH5_RECEIVE_ERROR");
///////////////////////////////////

// UART2 ERROR SENDING
#define E_UART2_BUSY 300
#define E_UART2_LOCKED 301
#define E_UART2_TIMEOUT 302
#define E_UART2_DMA1_CH7_TRANSMIT_ERROR 310
#define E_UART2_RECEIVE_ERROR_BASE 320 // Last 4 bits handles  ORE | NE | FE | PE in USART2_SR Page 818
  #define E_UART2_RECEIVE_ERROR_PARITY (E_UART2_RECEIVE_ERROR_BASE | PE)
  #define E_UART2_RECEIVE_ERROR_FRAME (E_UART2_RECEIVE_ERROR_BASE | FE)
  #define E_UART2_RECEIVE_ERROR_NOISE (E_UART2_RECEIVE_ERROR_BASE | NE)
  #define E_UART2_RECEIVE_ERROR_OVERUN (E_UART2_RECEIVE_ERROR_BASE | ORE)
#define E_UART2_RECEIVE_ERROR_BASE_LIMIT (E_UART2_RECEIVE_ERROR_PARITY|E_UART2_RECEIVE_ERROR_FRAME|E_UART2_RECEIVE_ERROR_NOISE|E_UART2_RECEIVE_ERROR_OVERUN)

#define E_UART2_DMA1_CH6_RECEIVE_ERROR 340

_Static_assert(E_UART2_DMA1_CH6_RECEIVE_ERROR > E_UART2_RECEIVE_ERROR_BASE_LIMIT, "Error number conflict E_UART2_DMA1_CH6_RECEIVE_ERROR");
///////////////////////////////////

// OLED ERRORS

#define E_OLED_BUFFER_TRANSFER_BUSY -50
#define E_OLED_BUFFER_TRANSFER_BUSY_TIMEOUT -51
#define E_OLED_BUFFER_BUSY_TIMEOUT -52
#define E_OLED_INIT_FAILED -53
#define E_OLED_NOT_INITIALIZED -54
#define E_OLED_CURSOR_PRINTF_LOCK_TIMEOUT -55
#define E_OLED_CURSOR_FLUSH_UPDATE_TIMEOUT -56

///////////////////////////////////

// STD OUT ERRORS

#define E_INVALID_OLED_PRINTF_BUF_SIZE -100
#define E_OLED_PRINTF_BUFFER_ACCESS_TIMEOUT -101
#define E_INVALID_OLED_CURSOR_PRINTF_BUF_SIZE -102
#define E_OLED_PRINTF_SET_CURSOR_FLUSH_BUSY -103 

///////////////////////////////////

// ERROR IN PROCESS
#define PROCESS_BUSY 90
///////////////////////////////////

// SYS QUEUE ERRORS
#define E_SYS_QUEUE_FULL 80
#define E_SYS_ADD_QUEUE_TIMEOUT_OR_GLOBAL_LOCK 81
#define E_SYS_RUN_QUEUE_TIMEOUT 84
#define E_SYS_ADD_QUEUE_NOT_RUNNING 85
#define E_SYS_QUEUE_QUEUE_OFF 86
///////////////////////////////////

// MASTER RS485 ERRORS
#define E_MASTER_MODBUS_BUSY 400
#define E_MASTER_INVALID_SLAVE_ADDRESS 401
#define E_MASTER_INVALID_NUMBER_OF_COILS 402
#define E_MASTER_INVALID_RECEIVE_SLAVE_ADDRESS 403
#define E_UNEXPECTED_READ_COILS_FUNCTION 404
#define E_INVALID_READ_COILS_DATA_SIZE 405
#define E_INVALID_READ_COILS_CRC 406
#define E_INVALID_READ_COILS_EXCEPTION_CRC 407
#define E_UNEXPECTED_READ_COILS_ERROR_CODE 408
#define E_UNEXPECTED_DISCRETE_INPUTS_FUNCTION 409
#define E_MASTER_INVALID_NUMBER_OF_DISCRETE_INPUTS 410
#define E_UNEXPECTED_READ_DISCRETE_INPUTS_ERROR_CODE 411
#define E_INVALID_DISCRETE_INPUTS_DATA_SIZE 412
#define E_INVALID_DISCRETE_INPUTS_CRC 413
#define E_INVALID_DISCRETE_INPUTS_EXCEPTION_CRC 414
#define E_UNEXPECTED_READ_HOLDING_REGISTERS_ERROR_CODE 415
#define E_UNEXPECTED_READ_HOLDING_REGISTERS_FUNCTION 416
#define E_INVALID_READ_HOLDING_REGISTERS_DATA_SIZE 417
#define E_INVALID_READ_HOLDING_REGISTERS_CRC 418
#define E_INVALID_READ_HOLDING_REGISTERS_EXCEPTION_CRC 419
#define E_MASTER_INVALID_NUMBER_OF_HOLDING_REGISTERS 420
#define E_MASTER_INVALID_NUMBER_OF_INPUT_REGISTERS 421
#define E_UNEXPECTED_READ_INPUT_REGISTERS_ERROR_CODE 422
#define E_UNEXPECTED_READ_INPUT_REGISTERS_FUNCTION 423
#define E_INVALID_READ_INPUT_REGISTERS_DATA_SIZE 424
#define E_INVALID_READ_INPUT_REGISTERS_CRC 425
#define E_INVALID_READ_INPUT_REGISTERS_EXCEPTION_CRC 426
#define E_INVALID_SINGLE_COIL_STATE 427
#define E_UNEXPECTED_WRITE_SINGLE_COIL_ERROR_CODE 428
#define E_UNEXPECTED_WRITE_SINGLE_COIL_FUNCTION 429
#define E_INVALID_WRITE_SINGLE_COIL_DATA_SIZE 430
#define E_INVALID_WRITE_SINGLE_COIL_CRC 431
#define E_INVALID_EXCEPTION_WRITE_SINGLE_COIL_CRC_CHECK 432
#define E_UNEXPECTED_WRITE_SINGLE_REGISTER_ERROR_CODE 433
#define E_UNEXPECTED_WRITE_SINGLE_REGISTER_FUNCTION 434
#define E_INVALID_WRITE_SINGLE_REGISTER_DATA_SIZE 435
#define E_INVALID_WRITE_SINGLE_REGISTER_CRC 436
#define E_INVALID_EXCEPTION_WRITE_SINGLE_REGISTER_CRC_CHECK 437
#define E_INVALID_WRITE_MULTIPLE_COILS_LIMIT 438
#define E_INVALID_WRITE_MULTIPLE_REGISTER_LIMIT 439
#define E_UNEXPECTED_WRITE_MULTIPLE_COILS_ERROR_CODE 440
#define E_UNEXPECTED_WRITE_MULTIPLE_COILS_FUNCTION 441
#define E_INVALID_WRITE_MULTIPLE_COILS_DATA_SIZE 442
#define E_INVALID_WRITE_MULTIPLE_COILS_CRC 443
#define E_INVALID_EXCEPTION_WRITE_MULTIPLE_COILS_CRC_CHECK 444
#define E_UNEXPECTED_WRITE_MULTIPLE_REGISTERS_ERROR_CODE 445
#define E_UNEXPECTED_WRITE_MULTIPLE_REGISTERS_FUNCTION 446
#define E_INVALID_WRITE_MULTIPLE_REGISTERS_DATA_SIZE 447
#define E_INVALID_WRITE_MULTIPLE_REGISTERS_CRC 448
#define E_INVALID_EXCEPTION_WRITE_MULTIPLE_REGISTERS_CRC_CHECK 449
#define E_INVALID_READ_WRITE_MULTIPLE_REGISTER_LIMIT_RD 450
#define E_INVALID_READ_WRITE_MULTIPLE_REGISTER_LIMIT_WR 451
#define E_UNEXPECTED_READ_OR_WRITE_MULTIPLE_REGISTERS_ERROR_CODE 452
#define E_UNEXPECTED_READ_OR_WRITE_MULTIPLE_REGISTERS_FUNCTION 453
#define E_INVALID_READ_OR_WRITE_MULTIPLE_REGISTERS_DATA_SIZE 454
#define E_INVALID_READ_OR_WRITE_MULTIPLE_REGISTERS_CRC 455
#define E_INVALID_EXCEPTION_READ_OR_WRITE_MULTIPLE_REGISTERS_CRC_CHECK 456
#define E_UNIMPLEMENTED_MODBUS_FUNCTION 457
#define E_UNEXPECTED_FUNCTION 458
#define E_UNEXPECTED_RECEIVE_FUNCTION 459
#define E_RECEIVED_WRITE_DISCRETE_ADDRESS_MISMATCH 460
#define E_RECEIVED_WRITE_ADDRESS_MISMATCH 461
#define E_RS485_MASTER_DMA5_BUFFER_OVERFLOW 462

///////////////////////////////////

// SLAVE RS485 ERRORS
#define E_RS485_SLAVE_UART2_IRQ_ERROR 500
#define E_RS485_SLAVE_TIM3_IRQ_ERROR 501
#define E_RS485_INVALID_SLAVE_ADDRESS_SET_TO_ONE 502
#define E_RS485_SLAVE_DOES_NOT_MATCH 503
#define E_RS485_SLAVE_INVALID_CRC16 504
#define E_RS485_SLAVE_FUNCTION_CODE_NOT_SUPPORTED 505
#define E_RS485_SLAVE_QTY_OF_REGISTER_OUT_OF_BOUNDS 506
#define E_RS485_SLAVE_MEMORY_OUT_OF_BOUNDS 506
#define E_RS485_SLAVE_DMA6_BUFFER_OVERFLOW 507
#define E_RS485_SLAVE_MEMORY_BUSY 508
#define E_RS485_SLAVE_COPY_MEMORY_HOLDING_ADDRESS_TIMEOUT 509

///////////////////////////////////

///////////////////////////////////

// SLAVE RS485 ERRORS
#define E_EP_IP2000_READ_SENSORS_BUSY 600
#define E_EP_IP2000_READ_SENSORS_ELEM_NOT_MATCH 601
#define E_EP_IP2000_READ_STATUS_BUSY 602
#define E_EP_IP2000_READ_STATUS_ELEM_NOT_MATCH 603
#define E_EP_IP2000_READ_OVER_TEMPERATURE_BUSY 604
#define E_EP_IP2000_READ_OVERTEMP_ELEM_NOT_MATCH 605
#define E_EP_IP2000_READ_WRITE_COIL_NOT_MATCH 606
#define E_EP_IP2000_READ_COIL_BUSY 607
#define E_EP_IP2000_WRITE_COIL_BUSY 608

#define E_EPEVER_TRACER_6415AN_ELEM_NOT_MATCH 620
#define E_EPEVER_TRACER_6415AN_READ_RATED_DATUM_BUSY 621
#define E_EPEVER_TRACER_6415AN_REAL_TIME_DATA_BUSY 622
#define E_EPEVER_TRACER_6415AN_REAL_TIME_ELEM_NOT_MATCH 623
#define E_EPEVER_TRACER_6415AN_REAL_TIME_STATUS_ELEM_NOT_MATCH 624
#define E_EPEVER_TRACER_6415AN_REAL_TIME_STATUS_BUSY 625
#define E_EPEVER_TRACER_6415AN_STATISTICAL_PARAMETERS_BUSY 626
#define E_EPEVER_TRACER_6415AN_STATISTICAL_PARAMETERS_ELEM_NOT_MATCH 627

///////////////////////////////////

#define E_NOT_IMPLEMENTED -1

void error_handler(int);
void init_error_handler_queue();

#ifndef RTOS_SOLAR48
void run_error_handler();
#endif

#endif

