#include <sys_queue.h>
#include <solar48_config.h>
#include <stddef.h>
#include <errors.h>

#ifdef USE_USB_PRINTF_IN_ERROR_LOGS
 #include <usb_io.h>
#else
 #include <peripheral/ssd1306/oled_utils.h>
#endif

SYS_QUEUE error_handler_queue = {0};
static int error_list[MAX_ERROR_LOGS_INSTANCES];

#define ERROR_LIST_BEGIN &error_list[0]
#define ERROR_LIST_END &error_list[MAX_ERROR_LOGS_INSTANCES - 1]

static int *error_list_ptr = ERROR_LIST_BEGIN;

static int _error_handler(void *ctx)
{

#ifdef USE_USB_PRINTF_IN_ERROR_LOGS
  usb_printf("Error: %d\n", (int)*((int *)ctx));
#else
  oled_printf_cursor(0, 40, "Error: %d\n", (int)*((int *)*ctx));
#endif

  return 0;
}

void error_handler(int error)
{
  *error_list_ptr = error;
  if (sys_queue(&error_handler_queue, _error_handler, (void *)error_list_ptr, NULL))
    return;

  if (++error_list_ptr > ERROR_LIST_END)
    error_list_ptr = ERROR_LIST_BEGIN;
}

void init_error_handler_queue()
{
  sys_queue_init(&error_handler_queue, MAX_ERROR_LOGS_INSTANCES, false);
}

void run_error_handler()
{
  run_queue_run(&error_handler_queue);
}

#define SET_ERROR_LIST_NAME(name) { #name, name },
static struct error_list_name_t {
  char *error_name;
  int value;
} error_list_name [] = 
{
  // USB INITIALIZATION ERROR
  SET_ERROR_LIST_NAME(E_USB_INIT)
  SET_ERROR_LIST_NAME(E_USB_REGISTER_CLASS)
  SET_ERROR_LIST_NAME(E_USB_REGISTER_INTERFACE)
  SET_ERROR_LIST_NAME(E_USB_START)

  // USB TRANSMIT ERROR
  SET_ERROR_LIST_NAME(E_USB_TRANSMIT_BUSY)
  SET_ERROR_LIST_NAME(E_USB_TRANSMIT_FAIL)

  // USB HAL CALBACK ERROR
  SET_ERROR_LIST_NAME(E_USB_HAL_PCD_HS)

  // USB HAL RECEIVE ERROR
  SET_ERROR_LIST_NAME(E_USB_RECEIVE_ERROR)
 
  // USB HAL LOCK ERROR
  SET_ERROR_LIST_NAME(E_USB_LOCK_ERROR)

  // USB HAL RECEIVE PROCESS BUSY
  SET_ERROR_LIST_NAME(E_USB_RECEIVE_PROC_BUSY)

  // USB BYTE CHUNK SENDING
  SET_ERROR_LIST_NAME(E_USB_SEND_CHUNK_INIT_BUSY)
  SET_ERROR_LIST_NAME(E_USB_SEND_CHUNK_SEND_FAIL)
  SET_ERROR_LIST_NAME(E_USB_SEND_CHUNK_BUSY)
  SET_ERROR_LIST_NAME(E_USB_SEND_CHUNK_INIT_TIMEOUT)
  SET_ERROR_LIST_NAME(E_USB_SEND_CHUNK_TIMEOUT)

  // UART1 ERROR SENDING
  SET_ERROR_LIST_NAME(E_UART1_BUSY)
  SET_ERROR_LIST_NAME(E_UART1_LOCKED)
  SET_ERROR_LIST_NAME(E_UART1_TIMEOUT)
  SET_ERROR_LIST_NAME(E_UART1_DMA1_CH4_TRANSMIT_ERROR)
  SET_ERROR_LIST_NAME(E_UART1_RECEIVE_ERROR_BASE)
  SET_ERROR_LIST_NAME(E_UART1_RECEIVE_ERROR_PARITY)
  SET_ERROR_LIST_NAME(E_UART1_RECEIVE_ERROR_FRAME)
  SET_ERROR_LIST_NAME(E_UART1_RECEIVE_ERROR_NOISE)
  SET_ERROR_LIST_NAME(E_UART1_RECEIVE_ERROR_OVERUN)

  // UART2 ERROR SENDING
  SET_ERROR_LIST_NAME(E_UART2_BUSY)
  SET_ERROR_LIST_NAME(E_UART2_LOCKED)
  SET_ERROR_LIST_NAME(E_UART2_TIMEOUT)
  SET_ERROR_LIST_NAME(E_UART2_DMA1_CH7_TRANSMIT_ERROR)
  SET_ERROR_LIST_NAME(E_UART2_RECEIVE_ERROR_BASE)
  SET_ERROR_LIST_NAME(E_UART2_RECEIVE_ERROR_PARITY)
  SET_ERROR_LIST_NAME(E_UART2_RECEIVE_ERROR_FRAME)
  SET_ERROR_LIST_NAME(E_UART2_RECEIVE_ERROR_NOISE)
  SET_ERROR_LIST_NAME(E_UART2_RECEIVE_ERROR_OVERUN)

  // OLED ERRORS
  SET_ERROR_LIST_NAME(E_OLED_BUFFER_TRANSFER_BUSY)
  SET_ERROR_LIST_NAME(E_OLED_BUFFER_TRANSFER_BUSY_TIMEOUT)
  SET_ERROR_LIST_NAME(E_OLED_BUFFER_BUSY_TIMEOUT)
  SET_ERROR_LIST_NAME(E_OLED_INIT_FAILED)
  SET_ERROR_LIST_NAME(E_OLED_NOT_INITIALIZED)
  SET_ERROR_LIST_NAME(E_OLED_CURSOR_PRINTF_LOCK_TIMEOUT)
  SET_ERROR_LIST_NAME(E_OLED_CURSOR_FLUSH_UPDATE_TIMEOUT)

  // STD OUT ERRORS

  SET_ERROR_LIST_NAME(E_INVALID_OLED_PRINTF_BUF_SIZE)
  SET_ERROR_LIST_NAME(E_OLED_PRINTF_BUFFER_ACCESS_TIMEOUT)
  SET_ERROR_LIST_NAME(E_INVALID_OLED_CURSOR_PRINTF_BUF_SIZE)
  SET_ERROR_LIST_NAME(E_OLED_PRINTF_SET_CURSOR_FLUSH_BUSY) 

  // ERROR IN PROCESS
  SET_ERROR_LIST_NAME(PROCESS_BUSY)

  // SYS QUEUE ERRORS
  SET_ERROR_LIST_NAME(E_SYS_QUEUE_FULL)
  SET_ERROR_LIST_NAME(E_SYS_ADD_QUEUE_TIMEOUT_OR_GLOBAL_LOCK)
  SET_ERROR_LIST_NAME(E_SYS_RUN_QUEUE_TIMEOUT)
  SET_ERROR_LIST_NAME(E_SYS_ADD_QUEUE_NOT_RUNNING)
  SET_ERROR_LIST_NAME(E_SYS_QUEUE_QUEUE_OFF)

  // MASTER RS485 ERRORS
  SET_ERROR_LIST_NAME(E_MASTER_MODBUS_BUSY)
  SET_ERROR_LIST_NAME(E_MASTER_INVALID_SLAVE_ADDRESS)
  SET_ERROR_LIST_NAME(E_MASTER_INVALID_NUMBER_OF_COILS)
  SET_ERROR_LIST_NAME(E_MASTER_INVALID_RECEIVE_SLAVE_ADDRESS)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_COILS_FUNCTION)
  SET_ERROR_LIST_NAME(E_INVALID_READ_COILS_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_READ_COILS_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_READ_COILS_EXCEPTION_CRC)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_COILS_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_DISCRETE_INPUTS_FUNCTION)
  SET_ERROR_LIST_NAME(E_MASTER_INVALID_NUMBER_OF_DISCRETE_INPUTS)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_DISCRETE_INPUTS_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_INVALID_DISCRETE_INPUTS_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_DISCRETE_INPUTS_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_DISCRETE_INPUTS_EXCEPTION_CRC)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_HOLDING_REGISTERS_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_HOLDING_REGISTERS_FUNCTION)
  SET_ERROR_LIST_NAME(E_INVALID_READ_HOLDING_REGISTERS_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_READ_HOLDING_REGISTERS_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_READ_HOLDING_REGISTERS_EXCEPTION_CRC)
  SET_ERROR_LIST_NAME(E_MASTER_INVALID_NUMBER_OF_HOLDING_REGISTERS)
  SET_ERROR_LIST_NAME(E_MASTER_INVALID_NUMBER_OF_INPUT_REGISTERS)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_INPUT_REGISTERS_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_INPUT_REGISTERS_FUNCTION)
  SET_ERROR_LIST_NAME(E_INVALID_READ_INPUT_REGISTERS_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_READ_INPUT_REGISTERS_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_READ_INPUT_REGISTERS_EXCEPTION_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_SINGLE_COIL_STATE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_WRITE_SINGLE_COIL_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_WRITE_SINGLE_COIL_FUNCTION)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_SINGLE_COIL_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_SINGLE_COIL_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_EXCEPTION_WRITE_SINGLE_COIL_CRC_CHECK)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_WRITE_SINGLE_REGISTER_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_WRITE_SINGLE_REGISTER_FUNCTION)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_SINGLE_REGISTER_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_SINGLE_REGISTER_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_EXCEPTION_WRITE_SINGLE_REGISTER_CRC_CHECK)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_MULTIPLE_COILS_LIMIT)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_MULTIPLE_REGISTER_LIMIT)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_WRITE_MULTIPLE_COILS_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_WRITE_MULTIPLE_COILS_FUNCTION)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_MULTIPLE_COILS_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_MULTIPLE_COILS_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_EXCEPTION_WRITE_MULTIPLE_COILS_CRC_CHECK)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_WRITE_MULTIPLE_REGISTERS_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_WRITE_MULTIPLE_REGISTERS_FUNCTION)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_MULTIPLE_REGISTERS_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_WRITE_MULTIPLE_REGISTERS_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_EXCEPTION_WRITE_MULTIPLE_REGISTERS_CRC_CHECK)
  SET_ERROR_LIST_NAME(E_INVALID_READ_WRITE_MULTIPLE_REGISTER_LIMIT_RD)
  SET_ERROR_LIST_NAME(E_INVALID_READ_WRITE_MULTIPLE_REGISTER_LIMIT_WR)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_OR_WRITE_MULTIPLE_REGISTERS_ERROR_CODE)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_READ_OR_WRITE_MULTIPLE_REGISTERS_FUNCTION)
  SET_ERROR_LIST_NAME(E_INVALID_READ_OR_WRITE_MULTIPLE_REGISTERS_DATA_SIZE)
  SET_ERROR_LIST_NAME(E_INVALID_READ_OR_WRITE_MULTIPLE_REGISTERS_CRC)
  SET_ERROR_LIST_NAME(E_INVALID_EXCEPTION_READ_OR_WRITE_MULTIPLE_REGISTERS_CRC_CHECK)
  SET_ERROR_LIST_NAME(E_UNIMPLEMENTED_MODBUS_FUNCTION)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_FUNCTION)
  SET_ERROR_LIST_NAME(E_UNEXPECTED_RECEIVE_FUNCTION)
  SET_ERROR_LIST_NAME(E_RECEIVED_WRITE_DISCRETE_ADDRESS_MISMATCH)
  SET_ERROR_LIST_NAME(E_RECEIVED_WRITE_ADDRESS_MISMATCH)
  SET_ERROR_LIST_NAME(E_RS485_MASTER_DMA5_BUFFER_OVERFLOW)
  SET_ERROR_LIST_NAME(E_MASTER_TIMEOUT_OR_NOT_RESPONDNG_RECEIVE_SLAVE_ADDRESS)

  // RS485 IP2000 ERRORS
  SET_ERROR_LIST_NAME(E_EP_IP2000_READ_SENSORS_BUSY)
  SET_ERROR_LIST_NAME(E_EP_IP2000_READ_SENSORS_ELEM_NOT_MATCH)
  SET_ERROR_LIST_NAME(E_EP_IP2000_READ_STATUS_BUSY)
  SET_ERROR_LIST_NAME(E_EP_IP2000_READ_STATUS_ELEM_NOT_MATCH)
  SET_ERROR_LIST_NAME(E_EP_IP2000_READ_OVER_TEMPERATURE_BUSY)
  SET_ERROR_LIST_NAME(E_EP_IP2000_READ_OVERTEMP_ELEM_NOT_MATCH)
  SET_ERROR_LIST_NAME(E_EP_IP2000_READ_WRITE_COIL_NOT_MATCH)
  SET_ERROR_LIST_NAME(E_EP_IP2000_READ_COIL_BUSY)
  SET_ERROR_LIST_NAME(E_EP_IP2000_WRITE_COIL_BUSY)
  SET_ERROR_LIST_NAME(E_EP_ILLEGAL_IP2000_EP_IP2000_RECEIVE)
  SET_ERROR_LIST_NAME(E_EP_IP2000_JSON_BUF_OVERFLOW)
  SET_ERROR_LIST_NAME(E_EP_IP2000_JSON_UNABLE_TO_PARSE)
  SET_ERROR_LIST_NAME(E_EP_IP2000_STATUS_JSON_UNABLE_TO_PARSE)
  SET_ERROR_LIST_NAME(E_EP_IP2000_STATUS_JSON_BUF_OVERFLOW)
  SET_ERROR_LIST_NAME(E_EP_IP2000_OVER_TEMP_JSON_UNABLE_TO_PARSE)
  SET_ERROR_LIST_NAME(E_EP_IP2000_OVER_TEMP_JSON_BUF_OVERFLOW)
  SET_ERROR_LIST_NAME(E_EP_ILLEGAL_IP2000_EP_IP2000_STATUS_RECEIVE)
  SET_ERROR_LIST_NAME(E_EP_ILLEGAL_IP2000_EP_IP2000_OVR_TEMP_RECEIVE)
  SET_ERROR_LIST_NAME(E_EP_ILLEGAL_IP2000_EP_IP2000_RD_WR_COIL_RECEIVE)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_ELEM_NOT_MATCH)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_READ_RATED_DATUM_BUSY)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_REAL_TIME_DATA_BUSY)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_REAL_TIME_ELEM_NOT_MATCH)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_REAL_TIME_STATUS_ELEM_NOT_MATCH)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_REAL_TIME_STATUS_BUSY)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_STATISTICAL_PARAMETERS_BUSY)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_STATISTICAL_PARAMETERS_ELEM_NOT_MATCH)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_SETTING_PARAMETERS_BUSY)
  SET_ERROR_LIST_NAME(E_EPEVER_TRACER_6415AN_SETTING_PARAMETERS_ELEM_NOT_MATCH)

  //NUMBER FORMAT TYPES ERROR
  SET_ERROR_LIST_NAME(E_REAL_U32_PREC_STRING_BUFFER_TOO_SHORT)
  SET_ERROR_LIST_NAME(E_REAL_U32_PREC_STRING_FORMAT_ERROR)

  ///////////////////////////////////

  SET_ERROR_LIST_NAME(E_NOT_IMPLEMENTED)

  {NULL, 0}
};

char *error_name(int value)
{
  struct error_list_name_t *lst = &error_list_name[0];

  do {
    if (lst->value == value)
      return lst->error_name;

    ++lst;
  } while (lst->error_name);

  return "Unknown error code";
}

#undef SET_ERROR_LIST_NAME